# Generated by Django 5.0.3 on 2024-03-26 19:46

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "image",
                    models.ImageField(
                        default="courses/defaultPic.jpg", upload_to="courses/%Y/%M/%d/"
                    ),
                ),
                ("date", models.DateTimeField(auto_now=True)),
                ("avaible", models.BooleanField(default=True)),
            ],
        ),
    ]
