# Generated by Django 5.0.3 on 2024-03-27 22:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0004_course_tags"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="course",
            name="tags",
        ),
    ]
